name: Keep Render API Awake

on:
  schedule:
    - cron: "*/5 * * * *"   # runs every 10 minutes
  workflow_dispatch:         # lets you run manually from Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        run: |
          curl -s https://my-journal-1.onrender.com/public/health-check || true
